### PR TITLE
Added 256GB Support

### PR DESCRIPTION
**Pull request by JengaMasterG**
Confirmed 256GB works up until the development menu.
The UEFI shell loads, but not the development menu.

### CODE REVIEW

**Comment by gus33000** [comment]
Sounds good! thanks a lot <3

DeveloperMenu not loading shouldn't be related to the storage size in theory. If you get thrown into EFIShell, the UEFI might not have found your partition or detected the UFS, can you please take a picture of efishell just to check if every partition gets detected?

**Comment by JengaMasterG** [comment]
Here's a picture I took before expanding the esp size. Could it be an issue just for the 256GB models? Sorry it may be a bit blurry.

**Comment by gus33000** [comment]
Ok this sounds good, your UFS is detected, it's likely an issue with how you formatted the esp partition here or copied files

**Comment by gus33000** [comment]
Are you able to go back into twrp, run parted again, and do the "print" command, and show the output? just to triple check

**Comment by Simizfo** [comment]
Adding a question, by any chance have you got a message saying that there weren't enough sectors available, when creating the fat32 filesystem on the ESP partition?

**Comment by JengaMasterG** [comment]
> Adding a question, by any chance have you got a message saying that there weren't enough sectors available, when creating the fat32 filesystem on the ESP partition?

Yes!

**Comment by JengaMasterG** [comment]
> Are you able to go back into twrp, run parted again, and do the "print" command, and show the output? just to triple check

Here's the console log:
```
GNU Parted 3.2
Using /dev/block/sda
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) print                                                            
Model: TOSHIBA THGJFCT1T84BAICB (scsi)
Disk /dev/block/sda: 240GB
Sector size (logical/physical): 4096B/4096B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name      Flags
 1      24.6kB  32.8kB  8192B                ssd
 2      32.8kB  33.6MB  33.6MB  ext4         persist
 3      33.6MB  50.4MB  16.8MB               metadata
 4      50.4MB  50.9MB  524kB                frp
 5      50.9MB  51.9MB  1049kB               misc
 6      51.9MB  400MB   348MB   fat32        esp       boot, esp
 7      400MB   116GB   116GB   ntfs         win       msftdata
 8      116GB   240GB   124GB   ext4         userdata
```

**Comment by Simizfo** [comment]
I'd say it wants a 512MB partition at this point. You should try to make your ESP from 51.9 to 564MB. Please let me know how that goes.

**Comment by JengaMasterG** [comment]
Not sure what happened this time (could've been that I was on Linux terminal) but no FAT32 size errors happening on Windows cmd line.

**Comment by Simizfo** [comment]
Oooops. I didn't think I could push directly. I thought it was going to make a PR.

I'd merge your PR as it is right now, if my change is ok with you. 
It was made to avoid people believing this would work on Surface Duo 2.

**Comment by Simizfo** [comment]
Wheeeee! Done! Thank you! 😄

**Pull request merged**
